### ISSUE TITLE
Doesn't work in a browser

### ISSUE THREAD

**Issue by tzi** [Bikossor/PrismaJS#1]
Hi.

I've got this error message when I try to use it in a browser.

> ReferenceError: module is not defined

You probably should use browserify to make it compatible?

Thanks for this lib,
Thomas.

**Comment by Bikossor** [comment]
Hello Thomas,

Thanks for the information! You can temporarily fix it yourself by removing
the following part from the source code "module.export = Prisma" (located
at the end of the file). I'll fix this issue soon as possible!

Thanks that you're enjoying my library!
Have a good day! :)


Best regards,

André Lichtenthäler

Am 08.03.2018 10:12 vorm. schrieb "Thomas ZILLIOX" <notifications@github.com
